### ISSUE TITLE
ks init - Create configuration files for a keystone project

### ISSUE THREAD

**Issue by devx-opensource** [wearedevx/keystone#17]
- [x] keystone.yaml - YAML configuration file. See structure below
- [x] .keystone - Keystone folder holding the cache (files + .env) and a file pointing to the current environment. See structure below.
- [ ]  if not already present, add the folder `.keystone` to `.gitignore`

*keystone.yaml*

```yaml
---
projectId: djkfhkqjhgjhdgsjhgdsf
env:
- key: ALGOLIA_TOKEN
  strict: true
- SENTRY
files:
- config/credentials.json
- config/cert.ca
options:
  strict: true
```

*.keystone/*

```js
.keystone/
  |- environment // holds the current environment name
  |-  cache/ 
       |- .env // cache for all the environment variables
       |- [...other files] are secrets files to cache
```
